INSERT INTO PA165.SERVICETYPE ("NAME") 
	VALUES ('STK');

INSERT INTO PA165.SERVICETYPE ("NAME") 
	VALUES ('Vymena oleje');

INSERT INTO PA165.SERVICETYPE ("NAME") 
	VALUES ('Servisni prohlidka');

INSERT INTO PA165.VEHICLETYPE (MAXKM, "NAME") 
	VALUES (200000, 'Trida 1');

INSERT INTO PA165.VEHICLETYPE (MAXKM, "NAME") 
	VALUES (300000, 'Trida 2');

INSERT INTO PA165.VEHICLETYPE (MAXKM, "NAME") 
	VALUES (400000, 'Trida 3');

INSERT INTO PA165.EMPLOYEE (EMPLOYEEROLE, FAMILYNAME, FIRSTNAME, PASSWORD, USERNAME) 
	VALUES (2, 'John', 'Doe', 'doe', 'doe')
