
package cz.muni.fi.pa165.carmanagement.soap.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VehicleTypeManager", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", wsdlLocation = "http://localhost:9000/vehicleTypeManager?wsdl")
public class VehicleTypeManager_Service
    extends Service
{

    private final static URL VEHICLETYPEMANAGER_WSDL_LOCATION;
    private final static WebServiceException VEHICLETYPEMANAGER_EXCEPTION;
    private final static QName VEHICLETYPEMANAGER_QNAME = new QName("http://server.soap.carmanagement.pa165.fi.muni.cz/", "VehicleTypeManager");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/vehicleTypeManager?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VEHICLETYPEMANAGER_WSDL_LOCATION = url;
        VEHICLETYPEMANAGER_EXCEPTION = e;
    }

    public VehicleTypeManager_Service() {
        super(__getWsdlLocation(), VEHICLETYPEMANAGER_QNAME);
    }

    public VehicleTypeManager_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), VEHICLETYPEMANAGER_QNAME, features);
    }

    public VehicleTypeManager_Service(URL wsdlLocation) {
        super(wsdlLocation, VEHICLETYPEMANAGER_QNAME);
    }

    public VehicleTypeManager_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VEHICLETYPEMANAGER_QNAME, features);
    }

    public VehicleTypeManager_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VehicleTypeManager_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VehicleTypeManager
     */
    @WebEndpoint(name = "VehicleTypeManagerImplPort")
    public VehicleTypeManager getVehicleTypeManagerImplPort() {
        return super.getPort(new QName("http://server.soap.carmanagement.pa165.fi.muni.cz/", "VehicleTypeManagerImplPort"), VehicleTypeManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VehicleTypeManager
     */
    @WebEndpoint(name = "VehicleTypeManagerImplPort")
    public VehicleTypeManager getVehicleTypeManagerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.soap.carmanagement.pa165.fi.muni.cz/", "VehicleTypeManagerImplPort"), VehicleTypeManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VEHICLETYPEMANAGER_EXCEPTION!= null) {
            throw VEHICLETYPEMANAGER_EXCEPTION;
        }
        return VEHICLETYPEMANAGER_WSDL_LOCATION;
    }

}
