
package cz.muni.fi.pa165.carmanagement.soap.server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VehicleManager", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VehicleManager {


    /**
     * 
     * @param id
     * @return
     *     returns cz.muni.fi.pa165.carmanagement.soap.server.VehicleDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVehicle", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.GetVehicle")
    @ResponseWrapper(localName = "getVehicleResponse", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.GetVehicleResponse")
    @Action(input = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleManager/getVehicleRequest", output = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleManager/getVehicleResponse")
    public VehicleDto getVehicle(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param vehicleDto
     */
    @WebMethod
    @RequestWrapper(localName = "createVehicle", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.CreateVehicle")
    @ResponseWrapper(localName = "createVehicleResponse", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.CreateVehicleResponse")
    @Action(input = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleManager/createVehicleRequest", output = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleManager/createVehicleResponse")
    public void createVehicle(
        @WebParam(name = "vehicleDto", targetNamespace = "")
        VehicleDto vehicleDto);

    /**
     * 
     * @return
     *     returns java.util.List<cz.muni.fi.pa165.carmanagement.soap.server.VehicleDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllVehicles", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.FindAllVehicles")
    @ResponseWrapper(localName = "findAllVehiclesResponse", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.FindAllVehiclesResponse")
    @Action(input = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleManager/findAllVehiclesRequest", output = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleManager/findAllVehiclesResponse")
    public List<VehicleDto> findAllVehicles();

    /**
     * 
     * @param vehicleDto
     */
    @WebMethod
    @RequestWrapper(localName = "updateVehicle", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.UpdateVehicle")
    @ResponseWrapper(localName = "updateVehicleResponse", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.UpdateVehicleResponse")
    @Action(input = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleManager/updateVehicleRequest", output = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleManager/updateVehicleResponse")
    public void updateVehicle(
        @WebParam(name = "vehicleDto", targetNamespace = "")
        VehicleDto vehicleDto);

    /**
     * 
     * @param vehicleDto
     */
    @WebMethod
    @RequestWrapper(localName = "removeVehicle", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.RemoveVehicle")
    @ResponseWrapper(localName = "removeVehicleResponse", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.RemoveVehicleResponse")
    @Action(input = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleManager/removeVehicleRequest", output = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleManager/removeVehicleResponse")
    public void removeVehicle(
        @WebParam(name = "vehicleDto", targetNamespace = "")
        VehicleDto vehicleDto);

}
