
package cz.muni.fi.pa165.carmanagement.web.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeManager", targetNamespace = "http://soap.web.carmanagement.pa165.fi.muni.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeManager {


    /**
     * 
     * @param employeeDto
     */
    @WebMethod
    @RequestWrapper(localName = "createEmployee", targetNamespace = "http://soap.web.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.web.soap.CreateEmployee")
    @ResponseWrapper(localName = "createEmployeeResponse", targetNamespace = "http://soap.web.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.web.soap.CreateEmployeeResponse")
    @Action(input = "http://soap.web.carmanagement.pa165.fi.muni.cz/EmployeeManager/createEmployeeRequest", output = "http://soap.web.carmanagement.pa165.fi.muni.cz/EmployeeManager/createEmployeeResponse")
    public void createEmployee(
        @WebParam(name = "employeeDto", targetNamespace = "")
        EmployeeDto employeeDto);

    /**
     * 
     * @param id
     * @return
     *     returns cz.muni.fi.pa165.carmanagement.web.soap.EmployeeDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployee", targetNamespace = "http://soap.web.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.web.soap.GetEmployee")
    @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://soap.web.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.web.soap.GetEmployeeResponse")
    @Action(input = "http://soap.web.carmanagement.pa165.fi.muni.cz/EmployeeManager/getEmployeeRequest", output = "http://soap.web.carmanagement.pa165.fi.muni.cz/EmployeeManager/getEmployeeResponse")
    public EmployeeDto getEmployee(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @return
     *     returns java.util.List<cz.muni.fi.pa165.carmanagement.web.soap.EmployeeDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllEmployees", targetNamespace = "http://soap.web.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.web.soap.FindAllEmployees")
    @ResponseWrapper(localName = "findAllEmployeesResponse", targetNamespace = "http://soap.web.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.web.soap.FindAllEmployeesResponse")
    @Action(input = "http://soap.web.carmanagement.pa165.fi.muni.cz/EmployeeManager/findAllEmployeesRequest", output = "http://soap.web.carmanagement.pa165.fi.muni.cz/EmployeeManager/findAllEmployeesResponse")
    public List<EmployeeDto> findAllEmployees();

    /**
     * 
     * @param employeeDto
     */
    @WebMethod
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://soap.web.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.web.soap.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://soap.web.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.web.soap.UpdateEmployeeResponse")
    @Action(input = "http://soap.web.carmanagement.pa165.fi.muni.cz/EmployeeManager/updateEmployeeRequest", output = "http://soap.web.carmanagement.pa165.fi.muni.cz/EmployeeManager/updateEmployeeResponse")
    public void updateEmployee(
        @WebParam(name = "employeeDto", targetNamespace = "")
        EmployeeDto employeeDto);

    /**
     * 
     * @param employeeDto
     */
    @WebMethod
    @RequestWrapper(localName = "removeEmployee", targetNamespace = "http://soap.web.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.web.soap.RemoveEmployee")
    @ResponseWrapper(localName = "removeEmployeeResponse", targetNamespace = "http://soap.web.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.web.soap.RemoveEmployeeResponse")
    @Action(input = "http://soap.web.carmanagement.pa165.fi.muni.cz/EmployeeManager/removeEmployeeRequest", output = "http://soap.web.carmanagement.pa165.fi.muni.cz/EmployeeManager/removeEmployeeResponse")
    public void removeEmployee(
        @WebParam(name = "employeeDto", targetNamespace = "")
        EmployeeDto employeeDto);

}
