
package cz.muni.fi.pa165.carmanagement.web.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EmployeeManager", targetNamespace = "http://soap.web.carmanagement.pa165.fi.muni.cz/", wsdlLocation = "http://localhost:8080/pa165/EmployeeManager?wsdl")
public class EmployeeManager_Service
    extends Service
{

    private final static URL EMPLOYEEMANAGER_WSDL_LOCATION;
    private final static WebServiceException EMPLOYEEMANAGER_EXCEPTION;
    private final static QName EMPLOYEEMANAGER_QNAME = new QName("http://soap.web.carmanagement.pa165.fi.muni.cz/", "EmployeeManager");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/pa165/EmployeeManager?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYEEMANAGER_WSDL_LOCATION = url;
        EMPLOYEEMANAGER_EXCEPTION = e;
    }

    public EmployeeManager_Service() {
        super(__getWsdlLocation(), EMPLOYEEMANAGER_QNAME);
    }

    public EmployeeManager_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYEEMANAGER_QNAME, features);
    }

    public EmployeeManager_Service(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYEEMANAGER_QNAME);
    }

    public EmployeeManager_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYEEMANAGER_QNAME, features);
    }

    public EmployeeManager_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EmployeeManager_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EmployeeManager
     */
    @WebEndpoint(name = "EmployeeManagerImplPort")
    public EmployeeManager getEmployeeManagerImplPort() {
        return super.getPort(new QName("http://soap.web.carmanagement.pa165.fi.muni.cz/", "EmployeeManagerImplPort"), EmployeeManager.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EmployeeManager
     */
    @WebEndpoint(name = "EmployeeManagerImplPort")
    public EmployeeManager getEmployeeManagerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.web.carmanagement.pa165.fi.muni.cz/", "EmployeeManagerImplPort"), EmployeeManager.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYEEMANAGER_EXCEPTION!= null) {
            throw EMPLOYEEMANAGER_EXCEPTION;
        }
        return EMPLOYEEMANAGER_WSDL_LOCATION;
    }

}
