
package cz.muni.fi.pa165.carmanagement.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmployeeManagerImpl", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmployeeManagerImpl {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createEmployee", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.CreateEmployee")
    @ResponseWrapper(localName = "createEmployeeResponse", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.CreateEmployeeResponse")
    @Action(input = "http://soap.carmanagement.pa165.fi.muni.cz/EmployeeManagerImpl/createEmployeeRequest", output = "http://soap.carmanagement.pa165.fi.muni.cz/EmployeeManagerImpl/createEmployeeResponse")
    public void createEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        EmployeeDto arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cz.muni.fi.pa165.carmanagement.soap.EmployeeDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllEmployees", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.FindAllEmployees")
    @ResponseWrapper(localName = "findAllEmployeesResponse", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.FindAllEmployeesResponse")
    @Action(input = "http://soap.carmanagement.pa165.fi.muni.cz/EmployeeManagerImpl/findAllEmployeesRequest", output = "http://soap.carmanagement.pa165.fi.muni.cz/EmployeeManagerImpl/findAllEmployeesResponse")
    public List<EmployeeDto> findAllEmployees();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateEmployee", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.UpdateEmployee")
    @ResponseWrapper(localName = "updateEmployeeResponse", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.UpdateEmployeeResponse")
    @Action(input = "http://soap.carmanagement.pa165.fi.muni.cz/EmployeeManagerImpl/updateEmployeeRequest", output = "http://soap.carmanagement.pa165.fi.muni.cz/EmployeeManagerImpl/updateEmployeeResponse")
    public void updateEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        EmployeeDto arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeEmployee", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.RemoveEmployee")
    @ResponseWrapper(localName = "removeEmployeeResponse", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.RemoveEmployeeResponse")
    @Action(input = "http://soap.carmanagement.pa165.fi.muni.cz/EmployeeManagerImpl/removeEmployeeRequest", output = "http://soap.carmanagement.pa165.fi.muni.cz/EmployeeManagerImpl/removeEmployeeResponse")
    public void removeEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        EmployeeDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns cz.muni.fi.pa165.carmanagement.soap.EmployeeDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getEmployee", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.GetEmployee")
    @ResponseWrapper(localName = "getEmployeeResponse", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.GetEmployeeResponse")
    @Action(input = "http://soap.carmanagement.pa165.fi.muni.cz/EmployeeManagerImpl/getEmployeeRequest", output = "http://soap.carmanagement.pa165.fi.muni.cz/EmployeeManagerImpl/getEmployeeResponse")
    public EmployeeDto getEmployee(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
