
package cz.muni.fi.pa165.carmanagement.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VehicleTypeManagerImplService", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", wsdlLocation = "http://localhost:8080/pa165/ws/vehicleTypeManager?wsdl")
public class VehicleTypeManagerImplService
    extends Service
{

    private final static URL VEHICLETYPEMANAGERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VEHICLETYPEMANAGERIMPLSERVICE_EXCEPTION;
    private final static QName VEHICLETYPEMANAGERIMPLSERVICE_QNAME = new QName("http://soap.carmanagement.pa165.fi.muni.cz/", "VehicleTypeManagerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/pa165/ws/vehicleTypeManager?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VEHICLETYPEMANAGERIMPLSERVICE_WSDL_LOCATION = url;
        VEHICLETYPEMANAGERIMPLSERVICE_EXCEPTION = e;
    }

    public VehicleTypeManagerImplService() {
        super(__getWsdlLocation(), VEHICLETYPEMANAGERIMPLSERVICE_QNAME);
    }

    public VehicleTypeManagerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VEHICLETYPEMANAGERIMPLSERVICE_QNAME, features);
    }

    public VehicleTypeManagerImplService(URL wsdlLocation) {
        super(wsdlLocation, VEHICLETYPEMANAGERIMPLSERVICE_QNAME);
    }

    public VehicleTypeManagerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VEHICLETYPEMANAGERIMPLSERVICE_QNAME, features);
    }

    public VehicleTypeManagerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VehicleTypeManagerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VehicleTypeManagerImpl
     */
    @WebEndpoint(name = "VehicleTypeManagerImplPort")
    public VehicleTypeManagerImpl getVehicleTypeManagerImplPort() {
        return super.getPort(new QName("http://soap.carmanagement.pa165.fi.muni.cz/", "VehicleTypeManagerImplPort"), VehicleTypeManagerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VehicleTypeManagerImpl
     */
    @WebEndpoint(name = "VehicleTypeManagerImplPort")
    public VehicleTypeManagerImpl getVehicleTypeManagerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.carmanagement.pa165.fi.muni.cz/", "VehicleTypeManagerImplPort"), VehicleTypeManagerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VEHICLETYPEMANAGERIMPLSERVICE_EXCEPTION!= null) {
            throw VEHICLETYPEMANAGERIMPLSERVICE_EXCEPTION;
        }
        return VEHICLETYPEMANAGERIMPLSERVICE_WSDL_LOCATION;
    }

}
