
package cz.muni.fi.pa165.carmanagement.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VehicleManagerImpl", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VehicleManagerImpl {


    /**
     * 
     * @return
     *     returns java.util.List<cz.muni.fi.pa165.carmanagement.soap.VehicleDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllVehicles", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.FindAllVehicles")
    @ResponseWrapper(localName = "findAllVehiclesResponse", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.FindAllVehiclesResponse")
    @Action(input = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleManagerImpl/findAllVehiclesRequest", output = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleManagerImpl/findAllVehiclesResponse")
    public List<VehicleDto> findAllVehicles();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateVehicle", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.UpdateVehicle")
    @ResponseWrapper(localName = "updateVehicleResponse", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.UpdateVehicleResponse")
    @Action(input = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleManagerImpl/updateVehicleRequest", output = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleManagerImpl/updateVehicleResponse")
    public void updateVehicle(
        @WebParam(name = "arg0", targetNamespace = "")
        VehicleDto arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeVehicle", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.RemoveVehicle")
    @ResponseWrapper(localName = "removeVehicleResponse", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.RemoveVehicleResponse")
    @Action(input = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleManagerImpl/removeVehicleRequest", output = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleManagerImpl/removeVehicleResponse")
    public void removeVehicle(
        @WebParam(name = "arg0", targetNamespace = "")
        VehicleDto arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "createVehicle", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.CreateVehicle")
    @ResponseWrapper(localName = "createVehicleResponse", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.CreateVehicleResponse")
    @Action(input = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleManagerImpl/createVehicleRequest", output = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleManagerImpl/createVehicleResponse")
    public void createVehicle(
        @WebParam(name = "arg0", targetNamespace = "")
        VehicleDto arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns cz.muni.fi.pa165.carmanagement.soap.VehicleDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVehicle", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.GetVehicle")
    @ResponseWrapper(localName = "getVehicleResponse", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.GetVehicleResponse")
    @Action(input = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleManagerImpl/getVehicleRequest", output = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleManagerImpl/getVehicleResponse")
    public VehicleDto getVehicle(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
