
package cz.muni.fi.pa165.carmanagement.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VehicleManagerImplService", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", wsdlLocation = "http://localhost:8080/pa165/ws/vehicleManager?wsdl")
public class VehicleManagerImplService
    extends Service
{

    private final static URL VEHICLEMANAGERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VEHICLEMANAGERIMPLSERVICE_EXCEPTION;
    private final static QName VEHICLEMANAGERIMPLSERVICE_QNAME = new QName("http://soap.carmanagement.pa165.fi.muni.cz/", "VehicleManagerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/pa165/ws/vehicleManager?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VEHICLEMANAGERIMPLSERVICE_WSDL_LOCATION = url;
        VEHICLEMANAGERIMPLSERVICE_EXCEPTION = e;
    }

    public VehicleManagerImplService() {
        super(__getWsdlLocation(), VEHICLEMANAGERIMPLSERVICE_QNAME);
    }

    public VehicleManagerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VEHICLEMANAGERIMPLSERVICE_QNAME, features);
    }

    public VehicleManagerImplService(URL wsdlLocation) {
        super(wsdlLocation, VEHICLEMANAGERIMPLSERVICE_QNAME);
    }

    public VehicleManagerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VEHICLEMANAGERIMPLSERVICE_QNAME, features);
    }

    public VehicleManagerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VehicleManagerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VehicleManagerImpl
     */
    @WebEndpoint(name = "VehicleManagerImplPort")
    public VehicleManagerImpl getVehicleManagerImplPort() {
        return super.getPort(new QName("http://soap.carmanagement.pa165.fi.muni.cz/", "VehicleManagerImplPort"), VehicleManagerImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VehicleManagerImpl
     */
    @WebEndpoint(name = "VehicleManagerImplPort")
    public VehicleManagerImpl getVehicleManagerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.carmanagement.pa165.fi.muni.cz/", "VehicleManagerImplPort"), VehicleManagerImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VEHICLEMANAGERIMPLSERVICE_EXCEPTION!= null) {
            throw VEHICLEMANAGERIMPLSERVICE_EXCEPTION;
        }
        return VEHICLEMANAGERIMPLSERVICE_WSDL_LOCATION;
    }

}
