
package cz.muni.fi.pa165.carmanagement.soap;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VehicleTypeManagerImpl", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VehicleTypeManagerImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns cz.muni.fi.pa165.carmanagement.soap.VehicleTypeDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVehicleType", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.GetVehicleType")
    @ResponseWrapper(localName = "getVehicleTypeResponse", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.GetVehicleTypeResponse")
    @Action(input = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleTypeManagerImpl/getVehicleTypeRequest", output = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleTypeManagerImpl/getVehicleTypeResponse")
    public VehicleTypeDto getVehicleType(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @return
     *     returns java.util.List<cz.muni.fi.pa165.carmanagement.soap.VehicleTypeDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllVehicleTypes", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.FindAllVehicleTypes")
    @ResponseWrapper(localName = "findAllVehicleTypesResponse", targetNamespace = "http://soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.FindAllVehicleTypesResponse")
    @Action(input = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleTypeManagerImpl/findAllVehicleTypesRequest", output = "http://soap.carmanagement.pa165.fi.muni.cz/VehicleTypeManagerImpl/findAllVehicleTypesResponse")
    public List<VehicleTypeDto> findAllVehicleTypes();

}
