
package cz.muni.fi.pa165.carmanagement.soap.server;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VehicleTypeManager", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VehicleTypeManager {


    /**
     * 
     * @param id
     * @return
     *     returns cz.muni.fi.pa165.carmanagement.soap.server.VehicleTypeDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVehicleType", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.GetVehicleType")
    @ResponseWrapper(localName = "getVehicleTypeResponse", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.GetVehicleTypeResponse")
    @Action(input = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleTypeManager/getVehicleTypeRequest", output = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleTypeManager/getVehicleTypeResponse")
    public VehicleTypeDto getVehicleType(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @return
     *     returns java.util.List<cz.muni.fi.pa165.carmanagement.soap.server.VehicleTypeDto>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAllVehicleTypes", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.FindAllVehicleTypes")
    @ResponseWrapper(localName = "findAllVehicleTypesResponse", targetNamespace = "http://server.soap.carmanagement.pa165.fi.muni.cz/", className = "cz.muni.fi.pa165.carmanagement.soap.server.FindAllVehicleTypesResponse")
    @Action(input = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleTypeManager/findAllVehicleTypesRequest", output = "http://server.soap.carmanagement.pa165.fi.muni.cz/VehicleTypeManager/findAllVehicleTypesResponse")
    public List<VehicleTypeDto> findAllVehicleTypes();

}
